Parameters:

  BucketName:
    Type: String
    Description: S3 bucket name that hosts Lambda content

  Architecture:
    Type: String
    Description: Executable architecture for the Lambda function
    AllowedValues:
      - x86_64
      - arm64

  DomainName:
    Type: String
    Description: Domain that will host the server

Outputs:
  InvokeURL:
    Description: "Distribution Domain"
    Value: !Sub "${Distribution.DomainName}"

Resources:

  # Global Resources
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  EventQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 3600
      VisibilityTimeout: 60

  # IAM Roles
  APIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      Description: API Gateway Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  HTTPLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "HTTP Lambda Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:GetQueueAttributes"
                  - "sqs:SendMessage"
                Resource: !Sub "${EventQueue.Arn}"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"

  WebSocketLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "WebSocket Lambda Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:GetQueueAttributes"
                  - "sqs:SendMessage"
                Resource: !Sub "${EventQueue.Arn}"
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  EventLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Event Lambda Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:GetQueueAttributes"
                  - "sqs:ChangeMessageVisibility"
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                Resource: !Sub "${EventQueue.Arn}"
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}"
              - Effect: Allow
                Action:
                  - "execute-api:ManageConnections"
                Resource: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  # Lambdas
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Description: "Certificates and Keys"
      Content:
         S3Bucket: !Ref BucketName
         S3Key: CrossHostLambdaLayer.zip

  HTTPLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - !Ref Architecture
      Code:
        S3Bucket: !Ref BucketName
        S3Key: CrossHostHTTPLambda.zip
      Environment:
        Variables:
          LOG_LEVEL: info
          ROUTE_PREFIX: !Ref HTTPAPIStage
          DOMAIN: !Ref DomainName
      Description: "Handles HTTP requests from API Gateway"
      FunctionName: CrossHostHTTPLambda
      Handler: CrossHostHTTPLambda
      Layers:
        - !Ref LambdaLayer
      PackageType: Zip
      Role: !Sub "${HTTPLambdaRole.Arn}"
      Runtime: "provided.al2"
      LoggingConfig:
        LogGroup: !Ref HTTPLambdaLogGroup

  LambdaAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "${HTTPLambda.Arn}"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HTTPAPI}/*/*/*"

  WebSocketLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "${WebSocketLambda.Arn}"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*"

  HTTPLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/CrossHost/HTTP"
      RetentionInDays: 3

  WebSocketLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - !Ref Architecture
      Code:
        S3Bucket: !Ref BucketName
        S3Key: CrossHostWSLambda.zip
      Environment:
        Variables:
          LOG_LEVEL: info
          ROUTE_PREFIX: !Ref WebSocketAPIStage
          DOMAIN: !Ref DomainName
          DYNAMO_TABLE: !Ref DynamoDBTable
          EVENT_QUEUE_URL: !Ref EventQueue
      Description: "Handles WebSocket requests from API Gateway"
      FunctionName: CrossHostWSLambda
      Handler: CrossHostWSLambda
      Layers:
        - !Ref LambdaLayer
      PackageType: Zip
      Role: !Sub "${WebSocketLambdaRole.Arn}"
      Runtime: "provided.al2"
      LoggingConfig:
        LogGroup: !Ref WebSocketLambdaLogGroup

  WebSocketLambdaAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "${WebSocketLambda.Arn}"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*/*/*"

  WebSocketLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/CrossHost/WebSocket"
      RetentionInDays: 3

  EventLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - !Ref Architecture
      Code:
        S3Bucket: !Ref BucketName
        S3Key: CrossHostEventLambda.zip
      Environment:
        Variables:
          LOG_LEVEL: info
          DYNAMO_TABLE: !Ref DynamoDBTable
          EVENT_QUEUE_URL: !Ref EventQueue
          WEBSOCKET_API_URL: !Sub "https://${WebSocketAPI}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketAPIStage}"
      Description: "Handles events from SQS"
      FunctionName: CrossHostEventLambda
      Handler: CrossHostEventLambda
      Layers:
        - !Ref LambdaLayer
      PackageType: Zip
      Role: !Sub "${EventLambdaRole.Arn}"
      Runtime: "provided.al2"
      LoggingConfig:
        LogGroup: !Ref EventLambdaLogGroup

  EventLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/CrossHost/Event"
      RetentionInDays: 3

  EventLambdaSQSMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Sub "${EventQueue.Arn}"
      FunctionName: !Ref EventLambda

  # WebSocket API
  WebSocketAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: "CrossHost WebSocket API"
      Name: CrossHostWS
      ProtocolType: WEBSOCKET
      Version: 1
      RouteSelectionExpression: "$request.body.action"

  WebSocketAPIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketLambda.Arn}/invocations"
      ContentHandlingStrategy: CONVERT_TO_BINARY

  WebSocketAPIStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: APIGatewayAccount
    Properties:
      ApiId: !Ref WebSocketAPI
      AutoDeploy: true
      Description: "WebSocket Test Deployment"
      StageName: Test
      DefaultRouteSettings:
        DataTraceEnabled: false
        LoggingLevel: OFF

  DefaultWebSocketAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: "$default"
      Target: !Sub "integrations/${WebSocketAPIIntegration}"

  ConnectWebSocketAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: "$connect"
      Target: !Sub "integrations/${WebSocketAPIIntegration}"

  DisconnectWebSocketAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: "$disconnect"
      Target: !Sub "integrations/${WebSocketAPIIntegration}"

  # HTTP API
  APIGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt APIGatewayRole.Arn

  HTTPAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: "CrossHost HTTP API"
      Name: CrossHostHTTP
      ProtocolType: HTTP
      Version: 1

  HTTPAPIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HTTPAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "${HTTPLambda.Arn}"
      PayloadFormatVersion: "2.0"

  HTTPAPIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HTTPAPI
      AutoDeploy: true
      Description: "API Test Deployment"
      StageName: Test

  WellKnownAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "GET /.well-known/{resource}"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  NodeInfoDocumentAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "GET /nodeinfo/{version}"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  GetATProtoXRPCRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "GET /xrpc/{nsid}"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  PostATProtoXRPCRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "POST /xrpc/{nsid}"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  GetUserAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "GET /users/{id}"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  PostUserInboxAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "POST /users/{id}/inbox"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  GetUserOutboxAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "GET /users/{id}/outbox"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  GetUserOutboxContentsAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPAPI
      RouteKey: "GET /users/{id}/outbox/contents"
      Target: !Sub "integrations/${HTTPAPIIntegration}"

  # CloudFront Distribution
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${HTTPAPI}.execute-api.${AWS::Region}.amazonaws.com"
            Id: HTTPOrigin
            OriginPath: !Sub "/${HTTPAPIStage}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
          - DomainName: !Sub "${WebSocketAPI}.execute-api.${AWS::Region}.amazonaws.com"
            Id: WSOrigin
            OriginPath: !Sub "/${WebSocketAPIStage}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: HTTPOrigin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
        CacheBehaviors:
          - TargetOriginId: WSOrigin
            PathPattern: "/xrpc/com.atproto.sync.subscribeRepos"
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            Compress: false
            FunctionAssociations:
              - EventType: viewer-request
                FunctionARN: !Ref CloudFrontFunction
  
  # This function rewrites the url path so it can be correctly routed to the
  # WebSocket endpoint.
  CloudFrontFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: ClearWebSocketPath
      FunctionConfig:
        Comment: Removes URL path for API Gateway WebSocket API
        Runtime: cloudfront-js-2.0
      FunctionCode: |
        function handler(event) {
          var request = event.request;

          request.uri = '/';

          return request;
        }
      AutoPublish: true
